In [2]:
!pip install --upgrade jupyterthemes

Requirement already satisfied: jupyterthemes in /home/valdir/anaconda3/lib/python3.9/site-packages (0.20.0)
Requirement already satisfied: ipython>=5.4.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyterthemes) (7.31.1)
Requirement already satisfied: matplotlib>=1.4.3 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyterthemes) (3.6.2)
Requirement already satisfied: lesscpy>=0.11.2 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyterthemes) (0.15.1)
Requirement already satisfied: jupyter-core in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyterthemes) (5.1.1)
Requirement already satisfied: notebook>=5.6.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyterthemes) (6.5.2)
Requirement already satisfied: pexpect>4.3 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (5.7.1)
Requirement already satisfied: backcall in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (0.2.0)
Requirement already satisfied: matplotlib-inline in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (0.1.6)
Requirement already satisfied: decorator in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (5.1.1)
Requirement already satisfied: pickleshare in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (0.7.5)
Requirement already satisfied: pygments in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (65.6.3)
Requirement already satisfied: jedi>=0.16 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (0.18.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipython>=5.4.1->jupyterthemes) (3.0.36)
Requirement already satisfied: ply in /home/valdir/anaconda3/lib/python3.9/site-packages (from lesscpy>=0.11.2->jupyterthemes) (3.11)
Requirement already satisfied: pyparsing>=2.2.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (22.0)
Requirement already satisfied: pillow>=6.2.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (9.3.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (1.0.5)
Requirement already satisfied: fonttools>=4.22.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (4.25.0)
Requirement already satisfied: numpy>=1.19 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /home/valdir/anaconda3/lib/python3.9/site-packages (from matplotlib>=1.4.3->jupyterthemes) (0.11.0)
Requirement already satisfied: argon2-cffi in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (21.3.0)
Requirement already satisfied: ipykernel in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (6.19.2)
Requirement already satisfied: jupyter-client>=5.3.4 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (7.4.8)
Requirement already satisfied: jinja2 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (2.11.3)
Requirement already satisfied: tornado>=6.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (6.2)
Requirement already satisfied: ipython-genutils in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (0.2.0)
Requirement already satisfied: nbformat in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (5.7.0)
Requirement already satisfied: nbconvert>=5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (6.4.4)
Requirement already satisfied: prometheus-client in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (0.14.1)
Requirement already satisfied: nest-asyncio>=1.5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (1.5.6)
Requirement already satisfied: nbclassic>=0.4.7 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (0.4.8)
Requirement already satisfied: Send2Trash>=1.8.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (0.17.1)
Requirement already satisfied: pyzmq>=17 in /home/valdir/anaconda3/lib/python3.9/site-packages (from notebook>=5.6.0->jupyterthemes) (23.2.0)
Requirement already satisfied: platformdirs>=2.5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyter-core->jupyterthemes) (2.5.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.4.1->jupyterthemes) (0.8.3)
Requirement already satisfied: entrypoints in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyter-client>=5.3.4->notebook>=5.6.0->jupyterthemes) (0.4)
Requirement already satisfied: jupyter-server>=1.8 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (1.23.4)
Requirement already satisfied: notebook-shim>=0.1.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (0.2.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.8.4)
Requirement already satisfied: testpath in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.6.0)
Requirement already satisfied: defusedxml in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.7.1)
Requirement already satisfied: bleach in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (4.1.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (1.5.0)
Requirement already satisfied: jupyterlab-pygments in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.1.2)
Requirement already satisfied: beautifulsoup4 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=5.6.0->jupyterthemes) (4.11.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jinja2->notebook>=5.6.0->jupyterthemes) (2.0.1)
Requirement already satisfied: fastjsonschema in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbformat->notebook>=5.6.0->jupyterthemes) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /home/valdir/anaconda3/lib/python3.9/site-packages (from nbformat->notebook>=5.6.0->jupyterthemes) (4.16.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.4.1->jupyterthemes) (0.7.0)

Requirement already satisfied: wcwidth in /home/valdir/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.4.1->jupyterthemes) (0.2.5)
Requirement already satisfied: six>=1.5 in /home/valdir/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.3->jupyterthemes) (1.16.0)
Requirement already satisfied: argon2-cffi-bindings in /home/valdir/anaconda3/lib/python3.9/site-packages (from argon2-cffi->notebook>=5.6.0->jupyterthemes) (21.2.0)
Requirement already satisfied: debugpy>=1.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipykernel->notebook>=5.6.0->jupyterthemes) (1.5.1)
Requirement already satisfied: psutil in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipykernel->notebook>=5.6.0->jupyterthemes) (5.9.0)
Requirement already satisfied: comm>=0.1.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from ipykernel->notebook>=5.6.0->jupyterthemes) (0.1.2)
Requirement already satisfied: attrs>=17.4.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->notebook>=5.6.0->jupyterthemes) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->notebook>=5.6.0->jupyterthemes) (0.18.0)
Requirement already satisfied: websocket-client in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (0.58.0)
Requirement already satisfied: anyio<4,>=3.1.0 in /home/valdir/anaconda3/lib/python3.9/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (3.5.0)
Requirement already satisfied: cffi>=1.0.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=5.6.0->jupyterthemes) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in /home/valdir/anaconda3/lib/python3.9/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=5.6.0->jupyterthemes) (2.3.2.post1)
Requirement already satisfied: webencodings in /home/valdir/anaconda3/lib/python3.9/site-packages (from bleach->nbconvert>=5->notebook>=5.6.0->jupyterthemes) (0.5.1)
Requirement already satisfied: idna>=2.8 in /home/valdir/anaconda3/lib/python3.9/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (3.4)
Requirement already satisfied: sniffio>=1.1 in /home/valdir/anaconda3/lib/python3.9/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=5.6.0->jupyterthemes) (1.2.0)
Requirement already satisfied: pycparser in /home/valdir/anaconda3/lib/python3.9/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=5.6.0->jupyterthemes) (2.21)

In [2]:
#importar bibliotecas
import pandas as pd
import numpy as np
from sklearn import datasets

In [19]:
#importar base de dados de custo de vida
vendas = pd.read_csv('sales.csv')

In [ ]:
#Faça uma análise sobre os Parâmetros da população

In [23]:
vendas.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

#Amostragem simples aleatória

In [24]:
#faça uma amostra probabilística simples sem repetição com 40 unidades
amostra1 = vendas.sample(363, replace = True)

In [26]:
#Exibe tamanho da amostra
amostra1.shape

(363, 8)

In [27]:
#exibe primeiras 10 linhas do dataset
amostra1.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
2788,20,17-06-2011,2065191.27,0,66.41,3.842,208.126560,7.287
4718,33,26-10-2012,253731.13,0,73.70,4.301,131.193097,6.895
6360,45,27-05-2011,817653.25,0,69.70,3.985,185.860308,8.521
3852,27,31-08-2012,1731935.43,0,75.00,4.026,142.405448,8.239
3529,25,16-12-2011,997502.47,0,33.09,3.413,212.068504,7.082
3611,26,15-10-2010,937956.89,0,39.93,2.878,132.763355,8.149
3826,27,02-03-2012,1509323.09,0,40.07,3.983,141.387536,8.009
4783,34,29-04-2011,895973.02,0,57.73,3.781,128.999867,10.581
4258,30,23-03-2012,430222.97,0,62.96,3.787,220.924486,7.057
3248,23,20-01-2012,1146992.13,0,15.33,3.542,136.856419,4.261

In [ ]:
#Exiba as estatísticas da amostra

In [30]:
vendas.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

#Amostragem sistemática

In [28]:
# Faça uma Funçao para definir a amostragem sistemática
def amostragem_sistematica(df, step):
 
    indexes = np.arange(3, len(df), step = step)
    amostragem_sistematica = df.iloc[indexes]
    return amostragem_sistematica

amostra_sistematica = amostragem_sistematica(vendas, 3)
 
# Visualiza a função
amostra_sistematica.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635,8.106
9,1,09-04-2010,1545418.53,0,65.86,2.770,210.622857,7.808
12,1,30-04-2010,1425100.71,0,67.41,2.780,210.389546,7.808
15,1,21-05-2010,1399662.07,0,76.44,2.826,210.617093,7.808

In [ ]:
#Exiba as estatísticas da amostra

In [29]:
amostra_sistematica.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,2144.000000,2.144000e+03,2144.000000,2144.000000,2144.000000,2144.000000,2144.000000
mean,23.003265,1.048246e+06,0.069963,60.604151,3.359233,171.531869,7.998573
std,12.984448,5.647227e+05,0.255144,18.504837,0.459175,39.350455,1.877769
min,1.000000,2.135383e+05,0.000000,9.510000,2.472000,126.064000,3.879000
25%,12.000000,5.536219e+05,0.000000,47.205000,2.931000,131.735000,6.891000
50%,23.000000,9.614361e+05,0.000000,62.625000,3.445000,182.613463,7.874000
75%,34.000000,1.425226e+06,0.000000,74.905000,3.734000,212.640473,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.169392,14.313000