In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.formula.api as smf

In [2]:
limite = pd.read_excel('Limite_Credito_Dummy.xlsx')

In [3]:
limite.head()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,Escolaridade,Gênero,Região,LimitedoChequeEspecial
0,70,10736,5214,400,Fundamental_Medio,RJ,F,500
1,68,5000,5000,380,Fundamental_Medio,RJ,F,600
2,44,5800,5800,500,Fundamental_Medio,RJ,F,800
3,72,4300,4300,2000,Fundamental_Medio,RJ,F,1000
4,75,4400,4400,3000,Fundamental_Medio,RJ,F,1000

In [4]:
limite.shape

(48, 8)

In [6]:
limites = pd.get_dummies(limite)

In [7]:
limites

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,Escolaridade_Fundamental_Medio,Escolaridade_Superior_Pos,Gênero_RJ,Gênero_SP,Região_F,Região_M
0,70,10736,5214,400,500,1,0,1,0,1,0
1,68,5000,5000,380,600,1,0,1,0,1,0
2,44,5800,5800,500,800,1,0,1,0,1,0
3,72,4300,4300,2000,1000,1,0,1,0,1,0
4,75,4400,4400,3000,1000,1,0,1,0,1,0
5,35,5000,5000,1000,1000,1,0,1,0,1,0
6,80,8100,8100,3500,1000,1,0,1,0,1,0
7,66,4800,4800,440,1500,1,0,1,0,1,0
8,39,6320,6320,1550,1640,1,0,1,0,1,0
9,47,5000,5000,2000,1700,1,0,0,1,1,0
10,65,8800,7300,2000,1780,1,0,0,1,1,0
11,81,6800,6800,380,2000,1,0,0,1,1,0
12,62,8784,8784,1170,2350,1,0,0,1,1,0
13,69,5000,5000,2000,2500,1,0,0,1,1,0
14,56,6000,6000,2000,2500,0,1,0,1,1,0
15,45,6400,6400,2000,2500,1,0,0,1,1,0
16,74,14584,10084,3000,2500,1,0,0,1,1,0
17,32,6000,6000,2000,3000,1,0,0,1,1,0
18,70,7000,5500,340,3000,1,0,0,1,1,0
19,72,7825,7825,3000,3000,1,0,0,1,1,0
20,39,8000,6500,2000,3000,1,0,0,1,1,0
21,94,8000,8000,2000,3000,0,1,0,1,1,0
22,30,8000,8000,3000,3350,1,0,1,0,1,0
23,46,12000,12000,2000,3500,1,0,1,0,1,0
24,54,6000,6000,1790,3600,0,1,1,0,0,1
25,67,6500,6500,3000,4000,1,0,1,0,0,1
26,31,6927,6927,3000,4000,1,0,1,0,0,1
27,69,37000,22000,1000,4000,1,0,1,0,0,1
28,70,6900,6900,3000,4140,1,0,1,0,0,1
29,61,11000,7500,2000,4930,0,1,1,0,0,1
30,73,7890,7000,3000,5000,1,0,1,0,0,1
31,69,10000,10000,3000,5000,1,0,1,0,0,1
32,68,10527,4027,3000,5000,1,0,1,0,0,1
33,45,12913,12913,1970,5320,0,1,1,0,0,1
34,35,12000,9000,3000,6000,0,1,1,0,0,1
35,62,17800,14800,3000,6000,0,1,1,0,0,1
36,67,15400,10400,2000,8000,0,1,1,0,0,1
37,63,8700,5700,3000,9900,1,0,1,0,0,1
38,47,10000,10000,3000,10000,0,1,0,1,0,1
39,82,10000,10000,3000,10000,0,1,0,1,0,1
40,75,12200,9200,3000,10000,0,1,0,1,0,1
41,66,13348,13348,2990,10000,0,1,0,1,0,1
42,64,15000,15000,3000,10000,0,1,0,1,0,1
43,68,21950,21000,3000,10000,0,1,1,0,0,1
44,70,13500,13500,3100,13000,0,1,0,1,0,1
45,66,40000,40000,3000,18185,0,1,0,1,0,1
46,67,30000,30000,900,20000,0,1,0,1,0,1
47,80,81000,54500,2000,35000,0,1,0,1,0,1

In [8]:
limites.corr()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,Escolaridade_Fundamental_Medio,Escolaridade_Superior_Pos,Gênero_RJ,Gênero_SP,Região_F,Região_M
Idade,1.000000,0.239445,0.213186,0.057183,0.228117,-0.150088,0.150088,-0.196052,0.196052,-0.121217,0.121217
RendimentoTotal,0.239445,1.000000,0.960551,0.031041,0.858120,-0.396191,0.396191,-0.177798,0.177798,-0.406241,0.406241
Salario,0.213186,0.960551,1.000000,0.081792,0.888839,-0.475479,0.475479,-0.242621,0.242621,-0.424335,0.424335
LimitedeCreditoImediato,0.057183,0.031041,0.081792,1.000000,0.226990,-0.259433,0.259433,-0.001145,0.001145,-0.473326,0.473326
LimitedoChequeEspecial,0.228117,0.858120,0.888839,0.226990,1.000000,-0.598310,0.598310,-0.312566,0.312566,-0.591779,0.591779
Escolaridade_Fundamental_Medio,-0.150088,-0.396191,-0.475479,-0.259433,-0.598310,1.000000,-1.000000,0.237508,-0.237508,0.602464,-0.602464
Escolaridade_Superior_Pos,0.150088,0.396191,0.475479,0.259433,0.598310,-1.000000,1.000000,-0.237508,0.237508,-0.602464,0.602464
Gênero_RJ,-0.196052,-0.177798,-0.242621,-0.001145,-0.312566,0.237508,-0.237508,1.000000,-1.000000,-0.167248,0.167248
Gênero_SP,0.196052,0.177798,0.242621,0.001145,0.312566,-0.237508,0.237508,-1.000000,1.000000,0.167248,-0.167248
Região_F,-0.121217,-0.406241,-0.424335,-0.473326,-0.591779,0.602464,-0.602464,-0.167248,0.167248,1.000000,-1.000000
Região_M,0.121217,0.406241,0.424335,0.473326,0.591779,-0.602464,0.602464,0.167248,-0.167248,-1.000000,1.000000

In [10]:
funcao = "LimitedoChequeEspecial~ Idade+RendimentoTotal+Salario+LimitedeCreditoImediato+Escolaridade_Fundamental_Medio	+Escolaridade_Superior_Pos	+Gênero_RJ	+Gênero_SP	*Região_F	+Região_M"
modelo = smf.ols(formula=funcao, data=limites).fit()
modelo.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.910
Model:                                OLS   Adj. R-squared:                  0.892
Method:                     Least Squares   F-statistic:                     49.50
Date:                    Sun, 14 May 2023   Prob (F-statistic):           4.76e-18
Time:                            23:00:47   Log-Likelihood:                -428.34
No. Observations:                      48   AIC:                             874.7
Df Residuals:                          39   BIC:                             891.5
Df Model:                               8
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       1221.3620    679.958      1.796      0.080    -153.983    2596.707
Idade                             -9.0901     20.351     -0.447      0.658     -50.253      32.073
RendimentoTotal                    0.2040      0.093      2.189      0.035       0.016       0.392
Salario                            0.1455      0.133      1.091      0.282      -0.124       0.415
LimitedeCreditoImediato            0.2463      0.371      0.664      0.511      -0.504       0.997
Escolaridade_Fundamental_Medio   437.7944    551.087      0.794      0.432    -676.884    1552.472
Escolaridade_Superior_Pos        783.5676    566.702      1.383      0.175    -362.695    1929.830
Gênero_RJ                      -1963.3552    501.607     -3.914      0.000   -2977.950    -948.760
Gênero_SP                       3184.7173    770.456      4.134      0.000    1626.323    4743.111
Região_F                        -425.1846    571.820     -0.744      0.462   -1581.799     731.430
Gênero_SP:Região_F             -4374.5740   1331.140     -3.286      0.002   -7067.059   -1682.088
Região_M                        1646.5466    646.805      2.546      0.015     338.259    2954.834
==============================================================================
Omnibus:                       21.264   Durbin-Watson:                   1.840
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               97.132
Skew:                          -0.751   Prob(JB):                     8.09e-22
Kurtosis:                       9.805   Cond. No.                     7.36e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.44e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [12]:
funcao1 = "LimitedoChequeEspecial~ RendimentoTotal+Salario+LimitedeCreditoImediato+Escolaridade_Fundamental_Medio	+Escolaridade_Superior_Pos	+Gênero_RJ	+Gênero_SP	*Região_F	+Região_M"
modelo1 = smf.ols(formula=funcao1, data=limites).fit()
modelo1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.910
Model:                                OLS   Adj. R-squared:                  0.894
Method:                     Least Squares   F-statistic:                     57.69
Date:                    Sun, 14 May 2023   Prob (F-statistic):           6.62e-19
Time:                            23:03:23   Log-Likelihood:                -428.47
No. Observations:                      48   AIC:                             872.9
Df Residuals:                          40   BIC:                             887.9
Df Model:                               7
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                        998.1606    456.496      2.187      0.035      75.548    1920.773
RendimentoTotal                    0.1964      0.091      2.166      0.036       0.013       0.380
Salario                            0.1541      0.131      1.180      0.245      -0.110       0.418
LimitedeCreditoImediato            0.2410      0.367      0.656      0.515      -0.501       0.983
Escolaridade_Fundamental_Medio   328.8101    489.161      0.672      0.505    -659.821    1317.441
Escolaridade_Superior_Pos        669.3505    500.646      1.337      0.189    -342.493    1681.194
Gênero_RJ                      -2034.5846    470.801     -4.322      0.000   -2986.108   -1083.061
Gênero_SP                       3032.7452    684.311      4.432      0.000    1649.701    4415.790
Região_F                        -532.1116    514.077     -1.035      0.307   -1571.100     506.877
Gênero_SP:Região_F             -4338.0901   1315.270     -3.298      0.002   -6996.351   -1679.829
Região_M                        1530.2723    586.156      2.611      0.013     345.607    2714.937
==============================================================================
Omnibus:                       21.288   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               95.244
Skew:                          -0.764   Prob(JB):                     2.08e-21
Kurtosis:                       9.729   Cond. No.                     4.64e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.12e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [14]:
funcao2 = "LimitedoChequeEspecial~ RendimentoTotal+Salario+Escolaridade_Fundamental_Medio	+Escolaridade_Superior_Pos	+Gênero_RJ	+Gênero_SP	*Região_F	+Região_M"
modelo2 = smf.ols(formula=funcao2, data=limites).fit()
modelo2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.909
Model:                                OLS   Adj. R-squared:                  0.896
Method:                     Least Squares   F-statistic:                     68.18
Date:                    Sun, 14 May 2023   Prob (F-statistic):           9.42e-20
Time:                            23:05:23   Log-Likelihood:                -428.72
No. Observations:                      48   AIC:                             871.4
Df Residuals:                          41   BIC:                             884.5
Df Model:                               6
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       1217.6274    308.552      3.946      0.000     594.493    1840.761
RendimentoTotal                    0.1858      0.089      2.097      0.042       0.007       0.365
Salario                            0.1638      0.129      1.271      0.211      -0.096       0.424
Escolaridade_Fundamental_Medio   464.7000    440.082      1.056      0.297    -424.063    1353.463
Escolaridade_Superior_Pos        752.9273    480.803      1.566      0.125    -218.074    1723.928
Gênero_RJ                      -1956.9311    452.512     -4.325      0.000   -2870.799   -1043.064
Gênero_SP                       3174.5585    644.770      4.924      0.000    1872.419    4476.698
Região_F                        -564.7431    508.102     -1.111      0.273   -1590.875     461.389
Gênero_SP:Região_F             -4338.0891   1306.106     -3.321      0.002   -6975.824   -1700.354
Região_M                        1782.3705    439.638      4.054      0.000     894.503    2670.238
==============================================================================
Omnibus:                       24.005   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              119.641
Skew:                          -0.886   Prob(JB):                     1.05e-26
Kurtosis:                      10.529   Cond. No.                     4.80e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.03e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [16]:
funcao3 = "LimitedoChequeEspecial~ RendimentoTotal+Escolaridade_Fundamental_Medio	+Escolaridade_Superior_Pos	+Gênero_RJ	+Gênero_SP	+Região_F	+Região_M"
modelo3 = smf.ols(formula=funcao3, data=limites).fit()
modelo3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.872
Model:                                OLS   Adj. R-squared:                  0.860
Method:                     Least Squares   F-statistic:                     73.03
Date:                    Sun, 14 May 2023   Prob (F-statistic):           1.33e-18
Time:                            23:06:53   Log-Likelihood:                -436.94
No. Observations:                      48   AIC:                             883.9
Df Residuals:                          43   BIC:                             893.2
Df Model:                               4
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                        798.4094    209.639      3.808      0.000     375.631    1221.188
RendimentoTotal                    0.3180      0.030     10.493      0.000       0.257       0.379
Escolaridade_Fundamental_Medio  -268.6800    459.685     -0.584      0.562   -1195.723     658.363
Escolaridade_Superior_Pos       1067.0894    516.626      2.065      0.045      25.213    2108.966
Gênero_RJ                       -943.7494    384.002     -2.458      0.018   -1718.164    -169.335
Gênero_SP                       1742.1588    407.842      4.272      0.000     919.668    2564.650
Região_F                       -1409.8266    475.400     -2.966      0.005   -2368.561    -451.092
Região_M                        2208.2360    494.874      4.462      0.000    1210.227    3206.245
==============================================================================
Omnibus:                       26.453   Durbin-Watson:                   1.661
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               95.170
Skew:                          -1.220   Prob(JB):                     2.16e-21
Kurtosis:                       9.452   Cond. No.                     3.08e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.55e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [21]:
funcao4 = "LimitedoChequeEspecial~ Gênero_RJ+Salario+Gênero_SP	+Região_F	+Região_M-1"
modelo4 = smf.ols(formula=funcao4, data=limites).fit()
modelo4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.879
Model:                                OLS   Adj. R-squared:                  0.871
Method:                     Least Squares   F-statistic:                     106.7
Date:                    Sun, 14 May 2023   Prob (F-statistic):           3.24e-20
Time:                            23:17:43   Log-Likelihood:                -435.50
No. Observations:                      48   AIC:                             879.0
Df Residuals:                          44   BIC:                             886.5
Df Model:                               3
Covariance Type:                nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Gênero_RJ   -762.7325    361.748     -2.108      0.041   -1491.788     -33.677
Salario        0.4616      0.041     11.367      0.000       0.380       0.543
Gênero_SP   1633.0786    504.366      3.238      0.002     616.596    2649.561
Região_F   -1546.3828    359.891     -4.297      0.000   -2271.696    -821.070
Região_M    2416.7289    537.714      4.494      0.000    1333.037    3500.421
==============================================================================
Omnibus:                       11.932   Durbin-Watson:                   1.646
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               29.897
Skew:                          -0.402   Prob(JB):                     3.22e-07
Kurtosis:                       6.782   Cond. No.                     1.40e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.78e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""